### ISSUE TITLE
Issue with character ":" converting .yml sigma to search

### ISSUE THREAD

**Issue by ishusoka** [SigmaHQ/pySigma#55]
Hello,

I tried to convert a custom sigma rule into Splunk search, i got the following code

```
myuser@kali:~/sigma$ sigma convert -t splunk -p sysmon -s sigmarule.yml 
Parsing Sigma rules  [------------------------------------]    0%
Traceback (most recent call last):
  File "/home/myuser/.local/bin/sigma", line 8, in <module>
    sys.exit(main())
  File "/home/myuser/.local/lib/python3.9/site-packages/sigma/cli/main.py", line 15, in main
    cli()
  File "/home/myuser/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/myuser/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/myuser/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/myuser/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/myuser/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/myuser/.local/lib/python3.9/site-packages/sigma/cli/convert.py", line 81, in convert
    rule_collection = load_rules(input, file_pattern)
  File "/home/myuser/.local/lib/python3.9/site-packages/sigma/cli/rules.py", line 10, in load_rules
    rule_collection = SigmaCollection.load_ruleset(
  File "/home/myuser/.local/lib/python3.9/site-packages/sigma/collection.py", line 149, in load_ruleset
    sigma_collection = SigmaCollection.from_yaml(path.open(encoding="utf-8"), collect_errors, SigmaRuleLocation(path))
  File "/home/myuser/.local/lib/python3.9/site-packages/sigma/collection.py", line 84, in from_yaml
    return cls.from_dicts(list(yaml.safe_load_all(yaml_str)), collect_errors, source)
  File "/home/myuser/.local/lib/python3.9/site-packages/sigma/collection.py", line 51, in from_dicts
    parsed_rules.append(SigmaRule.from_dict(deep_dict_update(rule, global_rule), collect_errors, source))
  File "/home/myuser/.local/lib/python3.9/site-packages/sigma/rule.py", line 600, in from_dict
    tags = [ SigmaRuleTag.from_str(tag) for tag in rule.get("tags", list()) ],
  File "/home/myuser/.local/lib/python3.9/site-packages/sigma/rule.py", line 600, in <listcomp>
    tags = [ SigmaRuleTag.from_str(tag) for tag in rule.get("tags", list()) ],
  File "/home/myuser/.local/lib/python3.9/site-packages/sigma/rule.py", line 43, in from_str
    ns, n = tag.split(".", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```

By investigating my yml file, it seems there is an issue when we're using the character ":" in tags field
![pysigma_issue](https://user-images.githubusercontent.com/29402891/174085704-d91dcb64-6fa4-4230-ae73-3063b67c52bb.PNG)

I removed this character and it now works well

```
myuser@kali:/tmp$ sigma convert -t splunk -p sysmon -s sigmarule.yml 
Parsing Sigma rules  [####################################]  100%
EventID=1 ParentImage="*\\EXCEL.EXE" Image="*\\regsvr32.exe" CommandLine="* ..\\*"
```

Is it an issue identify from your side or a legit behavior ?

Thank you
Ishu

**Comment by thomaspatzke** [comment]
Tags in Sigma rules are [defined to be namespaced](https://github.com/SigmaHQ/sigma/wiki/Specification#tags), where the namespace is separated from the remaining tag by a dot. I've

* added a [namespace tlp](https://github.com/SigmaHQ/sigma/wiki/Tags#namespace-tlp) to the list of predefined tag namespaces.
* pySigma now (main branch, not yet released) raises a more specific SigmaValueError.
